/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get healthz */
        get: operations["get-healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 admin users */
        get: operations["get-v1-admin-users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 admin users by ID */
        get: operations["get-v1-admin-users-by-id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 admin workspaces */
        get: operations["get-v1-admin-workspaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 auth me */
        get: operations["get-v1-auth-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/box-spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 box spec */
        get: operations["get-v1-box-spec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/machine-provider-info/aws/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 machine provider info aws regions */
        get: operations["get-v1-machine-provider-info-aws-regions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/machine-provider-info/hetzner/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 machine provider info hetzner locations */
        get: operations["get-v1-machine-provider-info-hetzner-locations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/machine-provider-info/hetzner/server-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 machine provider info hetzner server types */
        get: operations["get-v1-machine-provider-info-hetzner-server-types"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 workspaces */
        get: operations["get-v1-workspaces"];
        put?: never;
        /** Post v1 workspaces */
        post: operations["post-v1-workspaces"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 workspaces by workspace ID */
        get: operations["get-v1-workspaces-by-workspace-id"];
        put?: never;
        post?: never;
        /** Delete v1 workspaces by workspace ID */
        delete: operations["delete-v1-workspaces-by-workspace-id"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/boxes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 workspaces by workspace ID boxes */
        get: operations["get-v1-workspaces-by-workspace-id-boxes"];
        put?: never;
        /** Post v1 workspaces by workspace ID boxes */
        post: operations["post-v1-workspaces-by-workspace-id-boxes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/boxes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 workspaces by workspace ID boxes by ID */
        get: operations["get-v1-workspaces-by-workspace-id-boxes-by-id"];
        put?: never;
        post?: never;
        /** Delete v1 workspaces by workspace ID boxes by ID */
        delete: operations["delete-v1-workspaces-by-workspace-id-boxes-by-id"];
        options?: never;
        head?: never;
        /** Patch v1 workspaces by workspace ID boxes by ID */
        patch: operations["patch-v1-workspaces-by-workspace-id-boxes-by-id"];
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/boxes/{id}/generate-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post v1 workspaces by workspace ID boxes by ID generate token */
        post: operations["post-v1-workspaces-by-workspace-id-boxes-by-id-generate-token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/boxes/{id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 workspaces by workspace ID boxes by ID logs */
        get: operations["get-v1-workspaces-by-workspace-id-boxes-by-id-logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/boxes/{id}/logs/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["logs-stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/machine-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 workspaces by workspace ID machine providers */
        get: operations["get-v1-workspaces-by-workspace-id-machine-providers"];
        put?: never;
        /** Post v1 workspaces by workspace ID machine providers */
        post: operations["post-v1-workspaces-by-workspace-id-machine-providers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/machine-providers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 workspaces by workspace ID machine providers by ID */
        get: operations["get-v1-workspaces-by-workspace-id-machine-providers-by-id"];
        put?: never;
        post?: never;
        /** Delete v1 workspaces by workspace ID machine providers by ID */
        delete: operations["delete-v1-workspaces-by-workspace-id-machine-providers-by-id"];
        options?: never;
        head?: never;
        /** Patch v1 workspaces by workspace ID machine providers by ID */
        patch: operations["patch-v1-workspaces-by-workspace-id-machine-providers-by-id"];
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/machines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 workspaces by workspace ID machines */
        get: operations["get-v1-workspaces-by-workspace-id-machines"];
        put?: never;
        /** Post v1 workspaces by workspace ID machines */
        post: operations["post-v1-workspaces-by-workspace-id-machines"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/machines/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 workspaces by workspace ID machines by ID */
        get: operations["get-v1-workspaces-by-workspace-id-machines-by-id"];
        put?: never;
        post?: never;
        /** Delete v1 workspaces by workspace ID machines by ID */
        delete: operations["delete-v1-workspaces-by-workspace-id-machines-by-id"];
        options?: never;
        head?: never;
        /** Patch v1 workspaces by workspace ID machines by ID */
        patch: operations["patch-v1-workspaces-by-workspace-id-machines-by-id"];
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/networks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 workspaces by workspace ID networks */
        get: operations["get-v1-workspaces-by-workspace-id-networks"];
        put?: never;
        /** Post v1 workspaces by workspace ID networks */
        post: operations["post-v1-workspaces-by-workspace-id-networks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/networks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 workspaces by workspace ID networks by ID */
        get: operations["get-v1-workspaces-by-workspace-id-networks-by-id"];
        put?: never;
        post?: never;
        /** Delete v1 workspaces by workspace ID networks by ID */
        delete: operations["delete-v1-workspaces-by-workspace-id-networks-by-id"];
        options?: never;
        head?: never;
        /** Patch v1 workspaces by workspace ID networks by ID */
        patch: operations["patch-v1-workspaces-by-workspace-id-networks-by-id"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AwsRegion: {
            Endpoint: string;
            OptInStatus: string;
            RegionName: string;
        };
        Box: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            box_spec: components["schemas"]["BoxSpec"];
            /** Format: date-time */
            created_at: string;
            dboxed_version: string;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            machine: number | null;
            name: string;
            /** Format: int64 */
            network: number | null;
            network_type: string | null;
            /** Format: int64 */
            workspace: number;
        };
        BoxFile: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            spec: components["schemas"]["BoxSpec"];
        };
        BoxSpec: {
            composeProjects?: string[] | null;
            dboxedBinaryHash?: string;
            dboxedBinaryUrl?: string;
            dns: components["schemas"]["DnsSpec"];
            fileBundles?: components["schemas"]["FileBundle"][] | null;
            infraImage?: string;
            logs?: components["schemas"]["LogsSpec"];
        };
        BoxToken: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            token: string;
        };
        CreateBox: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            name: string;
            /** Format: int64 */
            network?: number;
        };
        CreateMachine: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            aws?: components["schemas"]["CreateMachineAws"];
            /** Format: int64 */
            box: number;
            hetzner?: components["schemas"]["CreateMachineHetzner"];
            /** Format: int64 */
            machine_provider: number;
            name: string;
        };
        CreateMachineAws: {
            instance_type: string;
            /** Format: int64 */
            root_volume_size?: number;
            subnet_id: string;
        };
        CreateMachineHetzner: {
            server_location: string;
            server_type: string;
        };
        CreateMachineProvider: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            aws?: components["schemas"]["CreateMachineProviderAws"];
            hetzner?: components["schemas"]["CreateMachineProviderHetzner"];
            name: string;
            ssh_key_public?: string;
            type: string;
        };
        CreateMachineProviderAws: {
            aws_access_key_id: string;
            aws_secret_access_key: string;
            region: string;
            vpc_id: string;
        };
        CreateMachineProviderHetzner: {
            cloud_token: string;
            hetzner_network_name: string;
            robot_password?: string;
            robot_username?: string;
        };
        CreateNetwork: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            name: string;
            netbird?: components["schemas"]["CreateNetworkNetbird"];
            type: string;
        };
        CreateNetworkNetbird: {
            apiAccessToken?: string;
            apiUrl?: string;
            netbirdVersion: string;
        };
        CreateWorkspace: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            name: string;
        };
        DeprecationInfo: {
            /** Format: date-time */
            Announced: string;
            /** Format: date-time */
            UnavailableAfter: string;
        };
        DnsLibP2PSpec: Record<string, never>;
        DnsSpec: {
            hostname: string;
            libp2p?: components["schemas"]["DnsLibP2PSpec"];
            networkDomain: string;
            networkInterface: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             */
            status?: number;
            /** @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error. */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             */
            type: string;
        };
        FileBundle: {
            files: components["schemas"]["FileBundleEntry"][] | null;
            name: string;
            /** Format: int32 */
            rootGid: number;
            rootMode: string;
            /** Format: int32 */
            rootUid: number;
        };
        FileBundleEntry: {
            data?: string;
            /** Format: int64 */
            gid: number;
            mode: string;
            path: string;
            stringData?: string;
            type?: string;
            /** Format: int64 */
            uid: number;
        };
        Healthz: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            Ok: boolean;
        };
        HetznerLocation: {
            city: string;
            country: string;
            description: string;
            /** Format: int64 */
            id: number;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            name: string;
            network_zone: string;
        };
        ListBodyAwsRegion: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            items: components["schemas"]["AwsRegion"][] | null;
            /** Format: int64 */
            total_count: number;
        };
        ListBodyBox: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            items: components["schemas"]["Box"][] | null;
            /** Format: int64 */
            total_count: number;
        };
        ListBodyHetznerLocation: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            items: components["schemas"]["HetznerLocation"][] | null;
            /** Format: int64 */
            total_count: number;
        };
        ListBodyLogMetadata: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            items: components["schemas"]["LogMetadata"][] | null;
            /** Format: int64 */
            total_count: number;
        };
        ListBodyMachine: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            items: components["schemas"]["Machine"][] | null;
            /** Format: int64 */
            total_count: number;
        };
        ListBodyMachineProvider: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            items: components["schemas"]["MachineProvider"][] | null;
            /** Format: int64 */
            total_count: number;
        };
        ListBodyNetwork: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            items: components["schemas"]["Network"][] | null;
            /** Format: int64 */
            total_count: number;
        };
        ListBodyServerType: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            items: components["schemas"]["ServerType"][] | null;
            /** Format: int64 */
            total_count: number;
        };
        ListBodyUser: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            items: components["schemas"]["User"][] | null;
            /** Format: int64 */
            total_count: number;
        };
        ListBodyWorkspace: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            items: components["schemas"]["Workspace"][] | null;
            /** Format: int64 */
            total_count: number;
        };
        Location: {
            City: string;
            Country: string;
            Description: string;
            /** Format: int64 */
            ID: number;
            /** Format: double */
            Latitude: number;
            /** Format: double */
            Longitude: number;
            Name: string;
            NetworkZone: string;
        };
        LogMetadata: {
            fileName: string;
            format: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
        LogsBatch: {
            lines: components["schemas"]["LogsLine"][] | null;
            /** Format: int64 */
            seq?: number;
        };
        LogsError: {
            message: string;
        };
        LogsLine: {
            line: string;
            /** Format: date-time */
            time: string;
        };
        LogsNatsSpec: {
            logId: string;
            logStream: string;
            metadataKVStore: string;
            nkeySeed: string;
            url: string;
        };
        LogsSpec: {
            nats?: components["schemas"]["LogsNatsSpec"];
        };
        Machine: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            /** Format: int64 */
            box: number;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            machine_provider: number;
            machine_provider_type: string;
            name: string;
            /** Format: int64 */
            workspace: number;
        };
        MachineProvider: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            aws?: components["schemas"]["MachineProviderAws"];
            /** Format: date-time */
            created_at: string;
            hetzner?: components["schemas"]["MachineProviderHetzner"];
            /** Format: int64 */
            id: number;
            name: string;
            ssh_key_fingerprint: string | null;
            status: string;
            type: string;
            /** Format: int64 */
            workspace: number;
        };
        MachineProviderAws: {
            region: string;
            security_group_id: string | null;
            subnets: components["schemas"]["MachineProviderAwsSubnet"][] | null;
            vpc_cidr: string | null;
            vpc_id: string | null;
            vpc_name: string | null;
        };
        MachineProviderAwsSubnet: {
            availability_zone: string;
            cidr: string;
            /** Format: int64 */
            machine_provider: number;
            subnet_id: string;
            subnet_name: string | null;
        };
        MachineProviderHetzner: {
            cloud_subnet_cidr: string | null;
            hetzner_network_cidr: string | null;
            /** Format: int64 */
            hetzner_network_id: number | null;
            hetzner_network_name: string;
            hetzner_network_zone: string | null;
            robot_subnet_cidr: string | null;
            /** Format: int64 */
            robot_vswitch_id: number | null;
        };
        Network: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            id: number;
            name: string;
            netbird: components["schemas"]["NetworkNetbird"];
            status: string;
            type: string;
            /** Format: int64 */
            workspace: number;
        };
        NetworkNetbird: {
            apiUrl: string;
            netbirdVersion: string;
        };
        Price: {
            Currency: string;
            Gross: string;
            Net: string;
            VATRate: string;
        };
        ServerType: {
            Architecture: string;
            CPUType: string;
            /** Format: int64 */
            Cores: number;
            Deprecation: components["schemas"]["DeprecationInfo"];
            Description: string;
            /** Format: int64 */
            Disk: number;
            /** Format: int64 */
            ID: number;
            /** Format: int64 */
            IncludedTraffic: number;
            /** Format: float */
            Memory: number;
            Name: string;
            Pricings: components["schemas"]["ServerTypeLocationPricing"][] | null;
            StorageType: string;
        };
        ServerTypeLocationPricing: {
            Hourly: components["schemas"]["Price"];
            /** Format: int64 */
            IncludedTraffic: number;
            Location: components["schemas"]["Location"];
            Monthly: components["schemas"]["Price"];
            PerTBTraffic: components["schemas"]["Price"];
        };
        UpdateBox: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            boxSpec: components["schemas"]["BoxSpec"];
        };
        UpdateMachine: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
        };
        UpdateMachineProvider: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            aws?: components["schemas"]["UpdateMachineProviderAws"];
            hetzner?: components["schemas"]["UpdateMachineProviderHetzner"];
            ssh_key_public?: string;
        };
        UpdateMachineProviderAws: {
            aws_access_key_id?: string;
            aws_secret_access_key?: string;
        };
        UpdateMachineProviderHetzner: {
            cloud_token?: string;
            robot_password?: string;
            robot_username?: string;
        };
        UpdateNetwork: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            netbird?: components["schemas"]["UpdateNetworkNetbird"];
        };
        UpdateNetworkNetbird: {
            apiAccessToken?: string;
            netbirdVersion: string | null;
        };
        User: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            avatar: string;
            email: string;
            id: string;
            isAdmin?: boolean;
            name: string;
        };
        Workspace: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            access: components["schemas"]["WorkspaceAccess"][] | null;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            id: number;
            name: string;
        };
        WorkspaceAccess: {
            user: components["schemas"]["User"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Healthz"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-admin-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBodyUser"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-admin-users-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-admin-workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBodyWorkspace"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-auth-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-box-spec": {
        parameters: {
            query?: {
                token?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoxFile"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-machine-provider-info-aws-regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBodyAwsRegion"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-machine-provider-info-hetzner-locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBodyHetznerLocation"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-machine-provider-info-hetzner-server-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBodyServerType"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBodyWorkspace"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-v1-workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspace"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-workspaces-by-workspace-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-v1-workspaces-by-workspace-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-workspaces-by-workspace-id-boxes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The workspace id */
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBodyBox"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-v1-workspaces-by-workspace-id-boxes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The workspace id */
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBox"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Box"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-workspaces-by-workspace-id-boxes-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                /** @description The workspace id */
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Box"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-v1-workspaces-by-workspace-id-boxes-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                /** @description The workspace id */
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Box"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "patch-v1-workspaces-by-workspace-id-boxes-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                /** @description The workspace id */
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBox"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Box"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-v1-workspaces-by-workspace-id-boxes-by-id-generate-token": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                /** @description The workspace id */
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoxToken"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-workspaces-by-workspace-id-boxes-by-id-logs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                /** @description The workspace id */
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBodyLogMetadata"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "logs-stream": {
        parameters: {
            query?: {
                file?: string;
                seq?: number;
            };
            header?: never;
            path: {
                id: number;
                /** @description The workspace id */
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": ({
                        data: components["schemas"]["LogsError"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "error";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["LogsBatch"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "logs";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["LogMetadata"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "metadata";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    })[];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-workspaces-by-workspace-id-machine-providers": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The workspace id */
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBodyMachineProvider"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-v1-workspaces-by-workspace-id-machine-providers": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The workspace id */
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMachineProvider"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MachineProvider"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-workspaces-by-workspace-id-machine-providers-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                /** @description The workspace id */
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MachineProvider"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-v1-workspaces-by-workspace-id-machine-providers-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                /** @description The workspace id */
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MachineProvider"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "patch-v1-workspaces-by-workspace-id-machine-providers-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                /** @description The workspace id */
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMachineProvider"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MachineProvider"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-workspaces-by-workspace-id-machines": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The workspace id */
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBodyMachine"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-v1-workspaces-by-workspace-id-machines": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The workspace id */
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMachine"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Machine"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-workspaces-by-workspace-id-machines-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                /** @description The workspace id */
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Machine"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-v1-workspaces-by-workspace-id-machines-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                /** @description The workspace id */
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Machine"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "patch-v1-workspaces-by-workspace-id-machines-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                /** @description The workspace id */
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMachine"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Machine"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-workspaces-by-workspace-id-networks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The workspace id */
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBodyNetwork"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-v1-workspaces-by-workspace-id-networks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The workspace id */
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNetwork"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Network"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-workspaces-by-workspace-id-networks-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                /** @description The workspace id */
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Network"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-v1-workspaces-by-workspace-id-networks-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                /** @description The workspace id */
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Network"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "patch-v1-workspaces-by-workspace-id-networks-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                /** @description The workspace id */
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNetwork"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Network"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
