/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 auth me */
        get: operations["get-v1-auth-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cloud-provider-info/aws/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 cloud provider info aws regions */
        get: operations["get-v1-cloud-provider-info-aws-regions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cloud-provider-info/hetzner/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 cloud provider info hetzner locations */
        get: operations["get-v1-cloud-provider-info-hetzner-locations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cloud-provider-info/hetzner/server-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 cloud provider info hetzner server types */
        get: operations["get-v1-cloud-provider-info-hetzner-server-types"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 workspaces */
        get: operations["get-v1-workspaces"];
        put?: never;
        /** Post v1 workspaces */
        post: operations["post-v1-workspaces"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 workspaces by workspace ID */
        get: operations["get-v1-workspaces-by-workspace-id"];
        put?: never;
        post?: never;
        /** Delete v1 workspaces by workspace ID */
        delete: operations["delete-v1-workspaces-by-workspace-id"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/cloud-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 workspaces by workspace ID cloud providers */
        get: operations["get-v1-workspaces-by-workspace-id-cloud-providers"];
        put?: never;
        /** Post v1 workspaces by workspace ID cloud providers */
        post: operations["post-v1-workspaces-by-workspace-id-cloud-providers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/cloud-providers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get v1 workspaces by workspace ID cloud providers by ID */
        get: operations["get-v1-workspaces-by-workspace-id-cloud-providers-by-id"];
        put?: never;
        post?: never;
        /** Delete v1 workspaces by workspace ID cloud providers by ID */
        delete: operations["delete-v1-workspaces-by-workspace-id-cloud-providers-by-id"];
        options?: never;
        head?: never;
        /** Patch v1 workspaces by workspace ID cloud providers by ID */
        patch: operations["patch-v1-workspaces-by-workspace-id-cloud-providers-by-id"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AwsRegion: {
            Endpoint: string;
            OptInStatus: string;
            RegionName: string;
        };
        CloudProvider: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            aws?: components["schemas"]["CloudProviderAws"];
            /** Format: date-time */
            created_at: string;
            hetzner?: components["schemas"]["CloudProviderHetzner"];
            /** Format: int64 */
            id: number;
            name: string;
            ssh_key_fingerprint: string | null;
            status: string;
            type: string;
            /** Format: int64 */
            workspace: number;
        };
        CloudProviderAws: {
            region: string;
            security_group_id: string | null;
            subnets: components["schemas"]["CloudProviderAwsSubnet"][] | null;
            vpc_cidr: string | null;
            vpc_id: string | null;
            vpc_name: string | null;
        };
        CloudProviderAwsSubnet: {
            availability_zone: string;
            cidr: string;
            /** Format: int64 */
            cloud_provider: number;
            subnet_id: string;
            subnet_name: string | null;
        };
        CloudProviderHetzner: {
            cloud_subnet_cidr: string | null;
            hetzner_network_cidr: string | null;
            /** Format: int64 */
            hetzner_network_id: number | null;
            hetzner_network_name: string;
            hetzner_network_zone: string | null;
            robot_subnet_cidr: string | null;
            /** Format: int64 */
            robot_vswitch_id: number | null;
        };
        CreateCloudProvider: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            aws?: components["schemas"]["CreateCloudProviderAws"];
            hetzner?: components["schemas"]["CreateCloudProviderHetzner"];
            name: string;
            ssh_key_public?: string;
            type: string;
        };
        CreateCloudProviderAws: {
            aws_access_key_id: string;
            aws_secret_access_key: string;
            region: string;
            vpc_id: string;
        };
        CreateCloudProviderHetzner: {
            cloud_token: string;
            hetzner_network_name: string;
            robot_password?: string;
            robot_username?: string;
        };
        CreateWorkspace: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            name: string;
        };
        DeprecationInfo: {
            /** Format: date-time */
            Announced: string;
            /** Format: date-time */
            UnavailableAfter: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             */
            status?: number;
            /** @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error. */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             */
            type: string;
        };
        HetznerLocation: {
            city: string;
            country: string;
            description: string;
            /** Format: int64 */
            id: number;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            name: string;
            network_zone: string;
        };
        ListBodyAwsRegion: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            items: components["schemas"]["AwsRegion"][] | null;
            /** Format: int64 */
            total_count: number;
        };
        ListBodyCloudProvider: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            items: components["schemas"]["CloudProvider"][] | null;
            /** Format: int64 */
            total_count: number;
        };
        ListBodyHetznerLocation: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            items: components["schemas"]["HetznerLocation"][] | null;
            /** Format: int64 */
            total_count: number;
        };
        ListBodyServerType: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            items: components["schemas"]["ServerType"][] | null;
            /** Format: int64 */
            total_count: number;
        };
        ListBodyWorkspace: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            items: components["schemas"]["Workspace"][] | null;
            /** Format: int64 */
            total_count: number;
        };
        Location: {
            City: string;
            Country: string;
            Description: string;
            /** Format: int64 */
            ID: number;
            /** Format: double */
            Latitude: number;
            /** Format: double */
            Longitude: number;
            Name: string;
            NetworkZone: string;
        };
        Price: {
            Currency: string;
            Gross: string;
            Net: string;
            VATRate: string;
        };
        ResourceAccess: {
            roles: string[] | null;
        };
        ServerType: {
            Architecture: string;
            CPUType: string;
            /** Format: int64 */
            Cores: number;
            Deprecation: components["schemas"]["DeprecationInfo"];
            Description: string;
            /** Format: int64 */
            Disk: number;
            /** Format: int64 */
            ID: number;
            /** Format: int64 */
            IncludedTraffic: number;
            /** Format: float */
            Memory: number;
            Name: string;
            Pricings: components["schemas"]["ServerTypeLocationPricing"][] | null;
            StorageType: string;
        };
        ServerTypeLocationPricing: {
            Hourly: components["schemas"]["Price"];
            /** Format: int64 */
            IncludedTraffic: number;
            Location: components["schemas"]["Location"];
            Monthly: components["schemas"]["Price"];
            PerTBTraffic: components["schemas"]["Price"];
        };
        UpdateCloudProvider: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            aws?: components["schemas"]["UpdateCloudProviderAws"];
            hetzner?: components["schemas"]["UpdateCloudProviderHetzner"];
            ssh_key_public?: string;
        };
        UpdateCloudProviderAws: {
            aws_access_key_id?: string;
            aws_secret_access_key?: string;
        };
        UpdateCloudProviderHetzner: {
            cloud_token?: string;
            robot_password?: string;
            robot_username?: string;
            /** Format: int64 */
            robot_vswitch_id?: number;
        };
        User: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            avatar: string;
            email: string;
            name: string;
            resource_access: {
                [key: string]: components["schemas"]["ResourceAccess"];
            };
            sub: string;
        };
        Workspace: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            /** Format: int64 */
            id: number;
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-v1-auth-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-cloud-provider-info-aws-regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBodyAwsRegion"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-cloud-provider-info-hetzner-locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBodyHetznerLocation"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-cloud-provider-info-hetzner-server-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBodyServerType"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBodyWorkspace"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-v1-workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspace"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-workspaces-by-workspace-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-v1-workspaces-by-workspace-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-workspaces-by-workspace-id-cloud-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBodyCloudProvider"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-v1-workspaces-by-workspace-id-cloud-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCloudProvider"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudProvider"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-v1-workspaces-by-workspace-id-cloud-providers-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudProvider"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-v1-workspaces-by-workspace-id-cloud-providers-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudProvider"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "patch-v1-workspaces-by-workspace-id-cloud-providers-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCloudProvider"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudProvider"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
